do_toy_example = function(type1="type1", type2="type2", scar_color="#aaaaaa", type1_color = "#cd00cd", type2_color="#00ffff", scarSize=6, scSize = 2.5, width=500, height=500){
master <- Node$new('master', size=scarSize, fill=scar_color, Cell.type="NA")
 scarA <- master$AddChild('scarA', size=scarSize, fill=scar_color, Cell.type='NA')
	scarC <-  scarA$AddChild('scarC', size=scarSize, fill=scar_color, Cell.type='NA')
			scC1 = scarC$AddChild('scC1', size=scSize, fill=type1_color, Cell.type=type1)
			scC2 = scarC$AddChild('scC2', size=scSize, fill=type1_color, Cell.type=type1)
			scC3 = scarC$AddChild('scC3', size=scSize, fill=type1_color, Cell.type=type1)
			scC4 = scarC$AddChild('scC4', size=scSize, fill=type1_color, Cell.type=type1)
	scarD <-  scarA$AddChild('scarD', size=scarSize, fill=scar_color, Cell.type='NA')
			scD1 = scarD$AddChild('scD1', size=scSize, fill=type1_color, Cell.type=type1)
			scD2 = scarD$AddChild('scD2', size=scSize, fill=type1_color, Cell.type=type1)
			scD3 = scarD$AddChild('scD3', size=scSize, fill=type2_color, Cell.type=type2)
			scD4 = scarD$AddChild('scD4', size=scSize, fill=type2_color, Cell.type=type2)
	scA1 = scarA$AddChild('scA1', size=scSize, fill=type1_color, Cell.type=type1)
	scA2 = scarA$AddChild('scA2', size=scSize, fill=type1_color, Cell.type=type1)
	scA3 = scarA$AddChild('scA3', size=scSize, fill=type2_color, Cell.type=type2)
	scA4 = scarA$AddChild('scA4', size=scSize, fill=type2_color, Cell.type=type2)
 scarB <- master$AddChild('scarB', size=scarSize, fill=scar_color, Cell.type='NA')
	scarE <-  scarB$AddChild('scarE', size=scarSize, fill=scar_color, Cell.type='NA')
			scE1 = scarE$AddChild('scE1', size=scSize, fill=type1_color, Cell.type=type1)
			scE2 = scarE$AddChild('scE2', size=scSize, fill=type1_color, Cell.type=type1)
			scE3 = scarE$AddChild('scE3', size=scSize, fill=type2_color, Cell.type=type2)
			scE4 = scarE$AddChild('scE4', size=scSize, fill=type2_color, Cell.type=type2)
	scarF <-  scarB$AddChild('scarF', size=scarSize, fill=scar_color, Cell.type='NA')
			scF1 = scarF$AddChild('scF1', size=scSize, fill=type2_color, Cell.type=type2)
			scF2 = scarF$AddChild('scF2', size=scSize, fill=type2_color, Cell.type=type2)
			scF3 = scarF$AddChild('scF3', size=scSize, fill=type2_color, Cell.type=type2)
			scF4 = scarF$AddChild('scF4', size=scSize, fill=type2_color, Cell.type=type2)
	scB1 = scarB$AddChild('scB1', size=scSize, fill=type1_color, Cell.type=type1)
	scB2 = scarB$AddChild('scB2', size=scSize, fill=type1_color, Cell.type=type1)
	scB3 = scarB$AddChild('scB3', size=scSize, fill=type2_color, Cell.type=type2)
	scB4 = scarB$AddChild('scB4', size=scSize, fill=type2_color, Cell.type=type2)
 sc1 = master$AddChild('sc1', size=scSize, fill=type1_color, Cell.type=type1)
 sc2 = master$AddChild('sc2', size=scSize, fill=type1_color, Cell.type=type1)
 sc3 = master$AddChild('sc3', size=scSize, fill=type2_color, Cell.type=type2)
 sc4 = master$AddChild('sc4', size=scSize, fill=type2_color, Cell.type=type2)

# TODO sort children to have symmetrical trees
widget_sc = collapsibleTree(master, collapsed = F, pieSummary=F, pieNode=F, ctypes=unique(master$Get("Cell.type")), nodeSize='size', fill="fill", ct_colors=c(type2_color,type1_color), width=width, height=height)
widget_summary = collapsibleTree(master, collapsed = F, pieSummary=T, pieNode=T, ctypes=unique(master$Get("Cell.type")), ct_colors=c(type1_color,type2_color), width=width, height=height)
return(list(widget_sc, widget_summary))
}



