do_toy_example = function(){
master <- Node$new('master', Cell.type="NA")
 scarA <- master$AddChild('scarA', Cell.type='NA')
	scarC <-  scarA$AddChild('scarC', Cell.type='NA')
			scC1 = scarC$AddChild('scC1', Cell.type="blood")
			scC2 = scarC$AddChild('scC2', Cell.type="blood")
			scC3 = scarC$AddChild('scC3', Cell.type="blood")
			scC4 = scarC$AddChild('scC4', Cell.type="blood")
	scarD <-  scarA$AddChild('scarD', Cell.type='NA')
			scD1 = scarD$AddChild('scD1', Cell.type="blood")
			scD2 = scarD$AddChild('scD2', Cell.type="blood")
			scD3 = scarD$AddChild('scD3', Cell.type="bone")
			scD4 = scarD$AddChild('scD4', Cell.type="bone")
	scA1 = scarA$AddChild('scA1', Cell.type="blood")
	scA2 = scarA$AddChild('scA2', Cell.type="blood")
	scA3 = scarA$AddChild('scA3', Cell.type="bone")
	scA4 = scarA$AddChild('scA4', Cell.type="bone")
 scarB <- master$AddChild('scarB', Cell.type='NA')
	scarE <-  scarB$AddChild('scarE', Cell.type='NA')
			scE1 = scarE$AddChild('scE1', Cell.type="blood")
			scE2 = scarE$AddChild('scE2', Cell.type="blood")
			scE3 = scarE$AddChild('scE3', Cell.type="bone")
			scE4 = scarE$AddChild('scE4', Cell.type="bone")
	scarF <-  scarB$AddChild('scarF', Cell.type='NA')
			scF1 = scarF$AddChild('scF1', Cell.type="bone")
			scF2 = scarF$AddChild('scF2', Cell.type="bone")
			scF3 = scarF$AddChild('scF3', Cell.type="bone")
			scF4 = scarF$AddChild('scF4', Cell.type="bone")
	scB1 = scarB$AddChild('scB1', Cell.type="blood")
	scB2 = scarB$AddChild('scB2', Cell.type="blood")
	scB3 = scarB$AddChild('scB3', Cell.type="bone")
	scB4 = scarB$AddChild('scB4', Cell.type="bone")
 sc1 = master$AddChild('sc1', Cell.type="blood")
 sc2 = master$AddChild('sc2', Cell.type="blood")
 sc3 = master$AddChild('sc3', Cell.type="bone")
 sc4 = master$AddChild('sc4', Cell.type="bone")

widget_sc = collapsibleTree(master, collapsed = F, pieSummary=F, pieNode=T, ctypes=unique(master$Get("Cell.type")), ct_colors=c("#00ffff","#cd00cd"))
widget_summary = collapsibleTree(master, collapsed = F, pieSummary=F, pieNode=T, ctypes=unique(master$Get("Cell.type")), ct_colors=c("#00ffff","#cd00cd"))
return(widget_sc, widget_summary)
}
